set -x
osnadmin channel join --channelID mychannel --config-block ./channel-artifacts/genesis.block -o localhost:7055 --ca-file "/root/ruc/fabric-samples/raft-network/crypto-config/ordererOrganizations/example.com/tlsca/tlsca.example.com-cert.pem" --client-cert "/root/ruc/fabric-samples/raft-network/crypto-config/ordererOrganizations/example.com/orderers/orderer0.example.com/tls/server.crt" --client-key "/root/ruc/fabric-samples/raft-network/crypto-config/ordererOrganizations/example.com/orderers/orderer0.example.com/tls/server.key"

set -x
osnadmin channel join --channelID mychannel --config-block ./channel-artifacts/genesis.block -o localhost:7155 --ca-file "/root/ruc/fabric-samples/raft-network/crypto-config/ordererOrganizations/example.com/tlsca/tlsca.example.com-cert.pem" --client-cert "/root/ruc/fabric-samples/raft-network/crypto-config/ordererOrganizations/example.com/orderers/orderer0.example.com/tls/server.crt" --client-key "/root/ruc/fabric-samples/raft-network/crypto-config/ordererOrganizations/example.com/orderers/orderer0.example.com/tls/server.key"

set -x
osnadmin channel join --channelID mychannel --config-block ./channel-artifacts/genesis.block -o localhost:7255 --ca-file "/root/ruc/fabric-samples/raft-network/crypto-config/ordererOrganizations/example.com/tlsca/tlsca.example.com-cert.pem" --client-cert "/root/ruc/fabric-samples/raft-network/crypto-config/ordererOrganizations/example.com/orderers/orderer0.example.com/tls/server.crt" --client-key "/root/ruc/fabric-samples/raft-network/crypto-config/ordererOrganizations/example.com/orderers/orderer0.example.com/tls/server.key"

set -x
osnadmin channel join --channelID mychannel --config-block ./channel-artifacts/genesis.block -o localhost:7355 --ca-file "/root/ruc/fabric-samples/raft-network/crypto-config/ordererOrganizations/example.com/tlsca/tlsca.example.com-cert.pem" --client-cert "/root/ruc/fabric-samples/raft-network/crypto-config/ordererOrganizations/example.com/orderers/orderer0.example.com/tls/server.crt" --client-key "/root/ruc/fabric-samples/raft-network/crypto-config/ordererOrganizations/example.com/orderers/orderer0.example.com/tls/server.key"